GarageCooperative/Models/ArrivalJournalModels/ArrivalJournalView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GarageCooperative.Models.ArrivalJournalModels
{
    public class ArrivalJournalView
    {
            public string Status { get; set; }
            public List<ArrivalJournalRecord> journal { get; set; }
    }
}

GarageCooperative/Controllers/ArrivalJournalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageCooperative.Data;
using GarageCooperative.Models;
using Microsoft.AspNetCore.Authorization;
using GarageCooperative.Models.ArrivalJournalModels;

namespace GarageCooperative.Controllers
{
    [Authorize(Roles = "Администратор,Председатель,Охранник")]
    public class ArrivalJournalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArrivalJournalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Journals
        public async Task<IActionResult> Index(string status=null)
        {
            ArrivalJournalView view = new ArrivalJournalView
            {
                journal = _context.ArrivalJournal.Include(x => x.Box).ToList(),
                Status=status
            };
            return View(view);
        }

      /*  // GET: Journals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.ArrivalJournal
                .SingleOrDefaultAsync(m => m.Id == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }
        */
        // GET: Journals/Create
        public IActionResult Create(string status = null)
        {
            ArrivalJournalRecord record = new ArrivalJournalRecord();
            ArrivalJournalRecordView view = new ArrivalJournalRecordView
            {
                record = record,
                Status = status
            };
            return View(view);
        }

        // POST: Journals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ArrivalJournalRecordView view, string Purpose)
        {
            ArrivalJournalRecord record;
            Box box = _context.Boxes.SingleOrDefault(w => w.Number.Equals(view.BoxNumber));

            if (ModelState.IsValid)
            {
                if (box == null && view.BoxNumber!=null)
                {
                    record = new ArrivalJournalRecord
                    {
                        Name = view.record.Name,
                        CarNumber = view.record.CarNumber,
                        Purpose = Purpose
                    };
                    ArrivalJournalRecordView view1 = new ArrivalJournalRecordView
                    {
                        record = record,
                        Status = "Бокса с данным номером не существует",
                    };
                    return View(view1);
                }
                view.record.Data = DateTime.Now;
                if (view.BoxNumber != null) view.record.BoxId = box.Id;
                else view.record.Box = null;
                view.record.Purpose = Purpose;
                    _context.Add(view.record);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { status = "Запись успешно добавлена" });
            }
            record = new ArrivalJournalRecord
            {
                Name = view.record.Name,
                CarNumber = view.record.CarNumber,
                Purpose = view.record.Purpose
            };
            ArrivalJournalRecordView view2 = new ArrivalJournalRecordView
            {
                record = record,
                BoxNumber = view.BoxNumber
            };
            return View(view2);
        }

        // GET: Journals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.ArrivalJournal
                .SingleOrDefaultAsync(m => m.Id == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // POST: Journals/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var journal = await _context.ArrivalJournal.SingleOrDefaultAsync(m => m.Id == id);
            _context.ArrivalJournal.Remove(journal);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { status = "Запись успешно удалена" });
        }

        private bool JournalExists(int id)
        {
            return _context.ArrivalJournal.Any(e => e.Id == id);
        }

        public ActionResult Cancel() => RedirectToAction("Index");
    }
}

GarageCooperative/Views/ArrivalJournals/Create.cshtml
@model GarageCooperative.Models.ArrivalJournalModels.ArrivalJournalRecordView

@{
    ViewData["Title"] = "Добавление записи в журнал посещений";
}
<h2>@ViewData["Title"]</h2>
@if (Model.Status != null)
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model.Status
    </div>
}
<h5>Поля, помеченные <label style="color:#ff0000"> * </label>, обязательны для заполнения.</h5>
<hr />
<div class="row">
    <div class="col-md-5">
        <form asp-action="Create" asp-controller="ArrivalJournals">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.record.Id" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.record.Name" class="control-label">ФИО<label style="color:#ff0000"> * </label></label>
                <input type="text" asp-for="@Model.record.Name" class="form-control" />
                <span asp-validation-for="@Model.record.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.record.CarNumber" class="control-label">Номер машины<label style="color:#ff0000"> * </label></label>
                <input type="text" asp-for="@Model.record.CarNumber" class="form-control" />
                <span asp-validation-for="@Model.record.CarNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.BoxNumber" class="control-label">Номер бокса</label>
                <input type="text" asp-for="@Model.BoxNumber" class="form-control" />
                <span asp-validation-for="@Model.record.Box.Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.record.Purpose" class="control-label">Цель визита</label>
                <div>
                    <textarea placeholder="Введите цель визита..." autofocus spellcheck="false" name="Purpose" style="width:100%" rows="3"></textarea>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" name="submitBtn" asp-action="Create" asp-controller="ArrivalJournals" value="Добавить" class="btn btn-primary" />
                <input type="submit" name="submitBtn" asp-action="Index" asp-controller="ArrivalJournals" style="display: inline " formnovalidate="formnovalidate" value="Отмена" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GarageCooperative/Views/ArrivalJournals/Delete.cshtml
@model GarageCooperative.Models.ArrivalJournalRecord
@{
    ViewData["Title"] = "Удаление записи из журнала";
}

<h2>@ViewData["Title"]</h2>
<div class="row">

    <div class="form-group">

        <label>Вы уверены, что хотите удалить запись?</label>
    </div>

    <form style="display: inline " asp-action="DeleteConfirm" asp-controller="ArrivalJournals">
        <input type="hidden" asp-for="Id" />
        <input type="submit" name="btn" value="Удалить" class="btn btn-danger" />
    </form>
    <form style="display: inline " asp-action="Cancel" asp-controller="ArrivalJournals">
        <input type="submit" name="btn" value="Отмена" class="btn btn-default" />
    </form>
</div>

GarageCooperative/Views/ArrivalJournals/Index.cshtml
@model GarageCooperative.Models.ArrivalJournalModels.ArrivalJournalView

@{
    ViewData["Title"] = "Журнал посещений";
}
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
<h2> @ViewData["Title"]</h2>

<p>
    <h5> <a class="btn btn-sm btn-primary" asp-action="Create">Создать запись</a></h5>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Дата
            </th>
            <th>
                ФИО
            </th>
            <th>
                Номер машины
            </th>
            <th>
                Номер бокса
            </th>
            <th>
                Цель визита
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.journal.OrderByDescending(x => x.Data))
        {
            <tr>
                <td>
                    @item.Data
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.CarNumber
                </td>
                <td>
                    @if (@item.Box != null)
                    {
                        @item.Box.Number
                    }
                </td>
                <td>
                    @item.Purpose
                </td>
                @if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Администратор") ||
                  await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Председатель"))
                {
                    <td>
                        <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                    </td>
                }
                </tr>
            }
            </tbody>
        </table>