GarageCooperative/Models/CreditDebit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GarageCooperative.Models
{
    public class CreditDebit
    {
        public int Id { get; set; }
        [Required]
        public string Target { get; set; }
        [Required]
        public bool Credit { get; set; }
        public double Value { get; set; }

        public bool BuhAccepted { get; set; }
        public DateTime Data { get; set; }
        public DateTime ConfirmationData { get; set; }
    }
}

GarageCooperative/Models/CreditDebitModels/CreditDebitView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GarageCooperative.Models.CreditDebitModels
{
    public class CreditDebitView
    {
        public string Status { get; set; }
        public List<CreditDebit> list { get; set; }
        public double Balance { get; set; }

    }
}

GarageCooperative/Controllers/CreditDebitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageCooperative.Data;
using GarageCooperative.Models;
using Microsoft.AspNetCore.Authorization;
using GarageCooperative.Models.CreditDebitModels;
using GarageCooperative.Models.ArrivalJournalModels;

namespace GarageCooperative.Controllers
{
    [Authorize(Roles = "Администратор,Председатель,Охранник")]
    public class CreditDebitController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CreditDebitController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Journals
        public async Task<IActionResult> Index(string status = null)
        {
            CreditDebitView view = new CreditDebitView
            {
                list = _context.CreditDebit.ToList(),
                Status = status,
                Balance = _context.balance.FirstOrDefault().balance
            };
            return View(view);
        }
        // GET: Credits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var credit = await _context.CreditDebit
                .SingleOrDefaultAsync(m => m.Id == id);
            if (credit == null)
            {
                return NotFound();
            }

            return View(credit);
        }

        // GET: Credits/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Credits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreditDebit creditdebit)
        {
            
            if (ModelState.IsValid)
            {
                creditdebit.BuhAccepted = false;
                creditdebit.Data = DateTime.Now;
                _context.Add(creditdebit);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { status = "Запись успешно добавлена" });
            }
            return View(creditdebit);
        }

        // GET: Credits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var credit = await _context.CreditDebit.SingleOrDefaultAsync(m => m.Id == id);
            if (credit == null)
            {
                return NotFound();
            }
            CreditDebitRecordView view = new CreditDebitRecordView
            {
                record = credit,
                Balance = _context.balance.FirstOrDefault().balance
            };


            return View(credit);
        }

        // POST: Credits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreditDebitRecordView view)
        {

            if (ModelState.IsValid)
            
            {
                double Balance = _context.balance.FirstOrDefault().balance;
                if (view.record.BuhAccepted && view.record.Credit && view.record.Value>Balance)
                {
                    view.record.BuhAccepted = false;
                    view.Status = "Надостаточно средств на балансе";


                    CreditDebitRecordView view2 = new CreditDebitRecordView
                    {
                        record = view.record,
                        Balance = _context.balance.FirstOrDefault().balance
                    };
                    return View(view2);
                }
                if (view.record.BuhAccepted)
                {
                    view.record.ConfirmationData = DateTime.Now;
                    Balance balance = _context.balance.FirstOrDefault();
                    if (view.record.Credit) balance.balance -= view.record.Value;
                    else balance.balance += view.record.Value;
                    _context.Update(balance);
                    _context.Update(view.record);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            CreditDebitRecordView view1 = new CreditDebitRecordView
            {
                record = view.record,
                Balance = _context.balance.FirstOrDefault().balance
            };
            return View(view1);
        }
        // GET: Journals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.CreditDebit
                .SingleOrDefaultAsync(m => m.Id == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // POST: Journals/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var journal = await _context.CreditDebit.SingleOrDefaultAsync(m => m.Id == id);
            if (journal.BuhAccepted) return RedirectToAction("Index", new { status = "Нельзя удалить подтвержденную платежку" });
            _context.CreditDebit.Remove(journal);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { status = "Запись успешно удалена" });
        }


        public ActionResult Cancel() => RedirectToAction("Index");
    }
}

GarageCooperative/Views/CreditDebit/Create.cshtml
@model GarageCooperative.Models.CreditDebit;
@{
    ViewData["Title"] = "Создать запись о расходах/доходах";
}

<h2>Create</h2>

<h4>Credit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Target" class="control-label">Цель расходов/Источник дохода</label>
                <input asp-for="Target" class="form-control" />
                <span asp-validation-for="Target" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label">Размер(руб.)</label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credit" class="control-label">Расход/Доход</label>
                <input asp-for="Credit" class="form-control" />
                <span asp-validation-for="Credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать запись" class="btn btn-primary" />
                <input type="submit" name="submitBtn" asp-action="Index" asp-controller="CreditDebit" style="display: inline " formnovalidate="formnovalidate" value="Отмена" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GarageCooperative/Views/CreditDebit/Delete.cshtml
@model GarageCooperative.Models.Credit

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Credit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Target)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Target)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GarageCooperative/Views/CreditDebit/Details.cshtml
@model GarageCooperative.Models.CreditDebit

@{
    ViewData["Title"] = "Запись о расходах/доходах";
}

<form>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="@Model.Id" />
    <input type="hidden" asp-for="@Model.Data" />
    <div class="form-group">
        <label asp-for="@Model.Data" class="control-label"></label>
        <input asp-for="@Model.Data" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Target" class="control-label"></label>
        <input asp-for="@Model.Target" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Value" class="control-label"></label>
        <input asp-for="@Model.Value" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Value" class="control-label"></label>
        <input asp-for="@Model.Value" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="@Model.BuhAccepted" class="control-label"></label>
        <input asp-for="@Model.BuhAccepted" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="@Model.ConfirmationData" class="control-label"></label>
        <input asp-for="@Model.ConfirmationData" class="form-control" disabled />
    </div>
</form>

GarageCooperative/Views/CreditDebit/Edit.cshtml
@model GarageCooperative.Models.CreditDebitModels.CreditDebitRecordView
@{
    ViewData["Title"] = "Подтверждение записи расходов/доходов";
}

 @ViewData["Title"]
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.record.Id" />
            <div class="form-group">
                <label asp-for="@Model.record.Data" class="control-label"></label>
                <input asp-for="@Model.record.Data" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Credit" class="control-label"></label>
                <input asp-for="@Model.Credit" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="@Model.record.Target" class="control-label"></label>
                <input asp-for="@Model.record.Target" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.record.Data" class="control-label"></label>
                <input asp-for="@Model.record.Data" class="form-control" disabled />
            </div>
            <div class="form-group">
                <input type="submit" name="submitBtn" asp-action="Edit" asp-controller="CreditDebit" value="Сохранить" class="btn btn-primary" />
                <input type="submit" name="submitBtn" asp-action="Edit" asp-controller="CreditDebit" style="display: inline " formnovalidate="formnovalidate" value="Отмена" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GarageCooperative/Views/CreditDebit/Index.cshtml
@model GarageCooperative.Models.CreditDebitModels.CreditDebitView

@{
    ViewData["Title"] = "Расходы/Доходы";
}
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
<h2> @ViewData["Title"]</h2>

<p>
    <h5> <a class="btn btn-sm btn-primary" asp-action="Create">Создать запись</a></h5>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Дата
            </th>
            <th>
                Цель расходов/Источник дохода
            </th>
            <th>
                Значение
            </th>
            <th>
                Номер бокса
            </th>
            <th>
                Принято бухгалтером
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.list.OrderByDescending(x => x.Data))
        {
        <tr>
            <td>
                @item.Data
            </td>
            <td>
                @if (item.Credit)
        {
            @item.Value
}
else
{
        @item.Value

}
            </td>

            <td>
                @item.Target
            </td>
            <td>
                @item.BuhAccepted
            </td>
            <td>
                @item.ConfirmationData
            </td>
            @if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Администратор") ||
   await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Председатель"))
    {
    @if (!item.BuhAccepted)
    { 
        <td>
            <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
        </td>
    }
            }
        </tr>
        }
    </tbody>
</table>