GarageCooperative/Models/Passport.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GarageCooperative.Models
{
    public class Passport
    {
        public int Id { get; set; }
        public int Seria { get; set; }
        [Required]
        public int Number { get; set; }
        public string PlaceOfIssue { get; set; }
        public string PlaceOfBirth { get; set; }
        // [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy
        [DataType(DataType.Date)]
        public DateTime  DateOfIssue { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public int OwnerId { get; set; }
        [ForeignKey("OwnerId")]
        public Owner Owner { get; set; }
    }
}

GarageCooperative/Controllers/PassportsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GarageCooperative.Data;
using GarageCooperative.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GarageCooperative.Controllers
{
    [Authorize(Roles = "Администратор,Председатель")]
    public class PassportsController : Controller
    {
        private readonly ApplicationDbContext _context;
        IHostingEnvironment _appEnvironment;

        public PassportsController(ApplicationDbContext context, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET: Owners/Details/5
        public async Task<IActionResult> Edit(int? id, string status = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passport = _context.Passports.SingleOrDefault(m => m.Id == id);
            if (passport == null)
            {
                return NotFound();
            }

            return View(passport);
        }

        // GET: Owners/Details/5
        public async Task<IActionResult> Photo(int? id, string status = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passport = _context.Passports.SingleOrDefault(m => m.Id == id);
            if (passport == null)
            {
                return NotFound();
            }

            return View(passport);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Seria,Number,DateOfBirth,PlaceOfBirth,DateOfIssue,PlaceOfIssue,OwnerId,Photo1,Photo2")] Passport passport)
        {
            if (ModelState.IsValid)
            {
                _context.Update(passport);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Owners", new { id = passport.OwnerId, status = "Паспортные данные успешно изменены" });
            }
            return View(passport);
        }

        [HttpPost]
        public async Task<IActionResult> AddPhoto1(int? id, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                var passport = _context.Passports.SingleOrDefault(m => m.Id == id);
                // путь к папке Files
                string path = "/images/Owner" + passport.OwnerId +"Passport1.jpg";
                if (path == passport.Photo1) path = "/images/Owner" + passport.OwnerId + "Passport1_1.jpg";
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                passport.Photo1 = path;
                _context.Update(passport);
                _context.SaveChanges();
                return RedirectToAction("Photo", new { id = id, status = "Фото успешно загружено" });
            }

            return RedirectToAction("Photo", new { id = id, status = "Фото не загружено" });
        }

        [HttpPost]
        public async Task<IActionResult> AddPhoto2(int? id, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                var passport = _context.Passports.SingleOrDefault(m => m.Id == id);
                // путь к папке Files
                string path = "/images/Owner" + passport.OwnerId + "Passport2.jpg";
                if (path == passport.Photo1) path = "/images/Owner" + passport.OwnerId + "Passport2_1.jpg";
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                passport.Photo2 = path;
                _context.Update(passport);
                _context.SaveChanges();
                return RedirectToAction("Photo", new { id = id, status = "Фото успешно загружено" });
            }

            return RedirectToAction("Photo", new { id = id, status = "Фото не загружено" });
        }


        // GET: Owners/Create
        public IActionResult Create(int id)
        {
            Passport passport = new Passport();
            passport.OwnerId = id;
            return View(passport);
        }

        // POST: Owners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Passport passport)
        {
            if (ModelState.IsValid)
            {
                //var owner = _context.Owners.SingleOrDefault(w => w.Id == passport.OwnerId);
                //owner.Passport.Add(passport);
                // owner.Contract.Number = contractNumber;
                passport.Id = 0;
                _context.Add(passport);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Owners", new { id=passport.OwnerId, status = String.Format("Паспорт добавлен успешно") });
            }
            return View(passport);
        }

        public async Task<ActionResult> Delete(int id)
        {
            Passport passport = _context.Passports.SingleOrDefault(w => w.Id == id);
            return View(passport);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            var passport = _context.Passports.SingleOrDefault(m => m.Id == id);
            if (passport != null)
            {

                _context.Remove(passport);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Owners", new { id = passport.OwnerId, status = String.Format("Паспорт успешно удален") });
            }
            return RedirectToAction("Details", "Owners", new { id = passport.OwnerId, status = "Произошла ошибка" });

        }
        public ActionResult Cancel(int id)
        {
            return RedirectToAction("Details", "Owners", new { id = id });
        }

    }
}

GarageCooperative/Views/Passports/Create.cshtml
@model GarageCooperative.Models.Passport

@{
    ViewData["Title"] = "Добавление паспорта члена кооператива";
}

<h2>@ViewData["Title"]</h2>

<hr />
<div class="row">
    <div class="col-md-5">
        <h4>Основная информация</h4>
        <form asp-action="Create" asp-controller="Passports">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.OwnerId" />
            </div>
            <div class="form-group">
                <label asp-for="Seria" class="control-label">Серия</label>
                <input type="text" asp-for="Seria" class="form-control" />
                <span asp-validation-for="Seria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label">Номер</label>
                <input type="text" asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfBirth" class="control-label">Место рождения</label>
                <input type="text" asp-for="PlaceOfBirth" class="form-control" />
                <span asp-validation-for="PlaceOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Дата рождения</label>
                <input type="text" asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfIssue" class="control-label">Место выдачи</label>
                <input type="text" asp-for="PlaceOfIssue" class="form-control" />
                <span asp-validation-for="PlaceOfIssue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfIssue" class="control-label">Дата выдачи</label>
                <input type="text" asp-for="DateOfIssue" class="form-control" />
                <span asp-validation-for="DateOfIssue" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" name="submitBtn" asp-action="Create" asp-controller="Passports" value="Добавить" class="btn btn-primary" />
                <input type="submit" name="submitBtn" asp-action="Details" asp-controller="Owners" asp-route-id="@Model.OwnerId" style="display: inline " formnovalidate="formnovalidate" value="Отмена" class="btn btn-default" />
            </div>
        </form>
</div>
</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

GarageCooperative/Views/Passports/Delete.cshtml
@model GarageCooperative.Models.Passport
@{     
    ViewData["Title"] = "Удаление паспорта члена кооператива";
}

<h2>@ViewData["Title"]</h2>
<div class="row">

    <div class="form-group">

        <label>Вы уверены, что хотите удалить паспорт?</label>
    </div>

    <form style="display: inline " asp-action="DeleteConfirm" asp-controller="Passports">
        <input type="hidden" asp-for="Id" />
        <input type="submit" name="btn" value="Удалить" class="btn btn-danger" />
    </form>
    <form style="display: inline " asp-action="Cancel" asp-controller="Passports">
        <input type="submit" name="btn" value="Отмена" class="btn btn-default" />
    </form>
</div>

GarageCooperative/Views/Passports/Edit.cshtml
@model GarageCooperative.Models.Passport
@{
    ViewBag.Title = "Редактирование данных паспорта";
}
<div class="row">
    <div class="col-md-4">
        <h2>@ViewData["Title"]</h2>
        <form asp-action="Edit" asp-controller="Passports">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="OwnerId" />
                <input type="hidden" asp-for="Photo1" />
                <input type="hidden" asp-for="Photo2" />
            </div>
            <div class="form-group">
                <label asp-for="Seria" class="control-label">Серия</label>
                <input type="text" asp-for="Seria" class="form-control" />
                <span asp-validation-for="Seria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label">Номер</label>
                <input type="text" asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfBirth" class="control-label">Место рождения</label>
                <input type="text" asp-for="PlaceOfBirth" class="form-control" />
                <span asp-validation-for="PlaceOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Дата рождения</label>
                <input type="text" asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfIssue" class="control-label">Место выдачи</label>
                <input type="text" asp-for="PlaceOfIssue" class="form-control" />
                <span asp-validation-for="PlaceOfIssue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfIssue" class="control-label">Дата выдачи</label>
                <input type="text" asp-for="DateOfIssue" class="form-control" />
                <span asp-validation-for="DateOfIssue" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" name="submitBtn" asp-action="Edit" asp-controller="Passports" value="Сохранить" class="btn btn-primary" />
                <input type="submit" name="submitBtn" asp-action="Details" asp-controller="Owners"  asp-route-id="@Model.OwnerId" style="display: inline " formnovalidate="formnovalidate" value="Отмена" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

GarageCooperative/Views/Passports/Photo.cshtml
@model GarageCooperative.Models.Passport
@{
    ViewBag.Title = "Фото паспорта";
}
<div class="row">
    <div class="col-md-12">
        <h2>@ViewData["Title"]</h2>
        <style>
            .img-container {
                height: auto;
                width: 100%;
                background: white;
            }
        </style>
        <table class="table">
            <tbody>
                <tr>
                    <th><h4>Фото 1</h4></th>
                    <td align="right"><a class="btn btn-sm btn-primary" asp-controller="Owners" asp-action="Details" asp-route-id="@Model.OwnerId">Назад</a></td>
            </tbody>
        </table>

        @if (Model.Photo1 != null)
        {
            <div class="img-container">
                <img src="@Url.Content(@Model.Photo1)" style="width:inherit; height:inherit; border-radius: 10px;  border: 2px solid #4cff00;">
            </div>
        }
        else
        {
            <div class="img-container">
                <img src="~/images/NoPhoto.png" style="width:inherit; height:inherit; border-radius: 10px;  border: 2px solid #4cff00;">
            </div>
        }
        <form asp-action="AddPhoto1" asp-controller="Passports" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
            <label class="control-label">Фото</label>
            <input class="btn btn-sm btn-default" type="file" name="uploadedFile" style="display: inline" />
            <input class="btn btn-sm btn-default" type="submit" value="Загрузить фото" style="display: inline" />
        </form>
        <hr size="2" width=100% align="left">
        <h4>Фото 2</h4>
        @if (Model.Photo2 != null)
        {
            <div class="img-container">
                <img src="@Url.Content(@Model.Photo2)" style="width:inherit; height:inherit; border-radius: 10px;  border: 2px solid #4cff00;">
            </div>
        }
        else
        {
            <div class="img-container">
                <img src="~/images/NoPhoto.png" style="width:inherit; height:inherit; border-radius: 10px;  border: 2px solid #4cff00;">
            </div>
        }
        <form asp-action="AddPhoto2" asp-controller="Passports" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
            <label class="control-label">Фото</label>
            <input class="btn btn-sm btn-default" type="file" name="uploadedFile" style="display: inline" />
            <input class="btn btn-sm btn-default" type="submit" value="Загрузить фото" style="display: inline" />
        </form>
    </div>

</div>