GarageCooperative/Controllers/BoxesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageCooperative.Data;
using GarageCooperative.Models;
using Microsoft.AspNetCore.Authorization;

namespace GarageCooperative.Controllers
{
    [Authorize(Roles = "Администратор,Председатель")]
    public class BoxesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BoxesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Boxes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Boxes.Include(b => b.BoxType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Boxes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var box = await _context.Boxes
                .Include(b => b.BoxType)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (box == null)
            {
                return NotFound();
            }

            return View(box);
        }

           // GET: Boxes/Create
        public IActionResult Create()
        {
            ViewData["BoxTypeId"] = new SelectList(_context.BoxTypes, "Id", "Id");
            return View();
        }

        // POST: Boxes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,MuchEnergyConsumption,BoxTypeId")] Box box)
        {
            if (ModelState.IsValid)
            {
                _context.Add(box);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoxTypeId"] = new SelectList(_context.BoxTypes, "Id", "Id", box.BoxTypeId);
            return View(box);
        }
        // GET: Boxes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var box = await _context.Boxes.SingleOrDefaultAsync(m => m.Id == id);
            if (box == null)
            {
                return NotFound();
            }
            ViewData["BoxTypeId"] = new SelectList(_context.BoxTypes, "Id", "Id", box.BoxTypeId);
            return View(box);
        }

        // POST: Boxes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,MuchEnergyConsumption,BoxTypeId")] Box box)
        {
            if (id != box.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(box);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoxExists(box.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoxTypeId"] = new SelectList(_context.BoxTypes, "Id", "Id", box.BoxTypeId);
            return View(box);
        }

        // GET: Boxes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var box = await _context.Boxes
                .Include(b => b.BoxType)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (box == null)
            {
                return NotFound();
            }

            return View(box);
        }

        // POST: Boxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var box = await _context.Boxes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Boxes.Remove(box);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoxExists(int id)
        {
            return _context.Boxes.Any(e => e.Id == id);
        }
    }
}

GarageCooperative/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GarageCooperative.Data;
using GarageCooperative.Models;
using GarageCooperative.Models.CarsViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GarageCooperative.Controllers
{
    [Authorize(Roles = "Администратор,Охранник")]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarsController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public IActionResult Index()
        {
            EnterViewModel model = new EnterViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Check(EnterViewModel model)
        {
            List<Owner> selectedOwners = new List<Owner>();
            string Status;
            if (model.CarNumber != null || (model.CarModel != null && model.CarColor != null))
            {
                IQueryable<Owner> Owners = _context.Owners.Include(x => x.OwnerBoxRels).ThenInclude(y => y.Box).Include(x => x.Cars);

                foreach (Owner owner in Owners.ToList())
                {
                    List<Car> findedCars = owner.Cars.Where(y => (y.Model.Equals(model.CarModel, StringComparison.OrdinalIgnoreCase) && y.Color.Equals(model.CarColor, StringComparison.OrdinalIgnoreCase) ||
                    y.Number.Equals(model.CarNumber, StringComparison.OrdinalIgnoreCase))).ToList();
                    if (findedCars.Any())
                    {
                        selectedOwners.Add(owner);
                    }
                }
                if (selectedOwners.Any()) Status = null;
                else Status = "Не найдено совпадений";


            }
            else
                Status = "Введены неверные значения для поиска. Необходимо ввести номер машины или модель вместе с цветом машины";
            CheckViewModel model1 = new CheckViewModel()
            {
                Status = Status,
                CarColor = model.CarColor,
                CarModel = model.CarModel,
                CarNumber = model.CarNumber,
                selectedOwners = selectedOwners,
            };

           return View(model1); 

        }


        // GET: Owners/Create
        public IActionResult Create(int id)
        {
            Car car = new Car();
            car.OwnerId = id;
            return View(car);
        }

        // POST: Owners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                //var owner = _context.Owners.SingleOrDefault(w => w.Id == passport.OwnerId);
                //owner.Passport.Add(passport);
                // owner.Contract.Number = contractNumber;
                car.Id = 0;
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Owners", new { id = car.OwnerId, status = String.Format("Машина добавлена успешно") });
            }
            return View(car);
        }


        public async Task<ActionResult> Delete(int id)
        {
           Car car= _context.Cars.SingleOrDefault(w => w.Id == id);
            return View(car);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            Car car = _context.Cars.SingleOrDefault(w => w.Id == id);
            if (car != null)
            {

                _context.Remove(car);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Owners", new { id = car.OwnerId, status = String.Format("Машина успешно удалена") });
            }
            return RedirectToAction("Details", "Owners", new { id = car.OwnerId, status = "Произошла ошибка" });

        }
        public ActionResult Cancel(int id)
        {
            return RedirectToAction("Details", "Owners", new { id = id });
        }

        // GET: Owners/Details/5
        public async Task<IActionResult> Edit(int? id, string status = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = _context.Cars.SingleOrDefault(m => m.Id == id);
            if (car== null)
            {
                return NotFound();
            }

            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                _context.Update(car);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Owners", new { id = car.OwnerId, status = "Данные машины успешно изменены" });
            }
            return View(car);
        }


    }
}

GarageCooperative/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageCooperative.Data;
using GarageCooperative.Models;
using Microsoft.AspNetCore.Authorization;

namespace GarageCooperative.Controllers
{
    [Authorize(Roles = "Sec")]
    public class LogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LogsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Logs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Log.ToListAsync());
        }

        // GET: Logs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var log = await _context.Log
                .SingleOrDefaultAsync(m => m.Id == id);
            if (log == null)
            {
                return NotFound();
            }

            return View(log);
        }

        // GET: Logs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Logs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,GarageNumber,ContractNumber,BookNumber,ReleaseDate")] Log log)
        {
            if (ModelState.IsValid)
            {
                _context.Add(log);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(log);
        }

        // GET: Logs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var log = await _context.Log.SingleOrDefaultAsync(m => m.Id == id);
            if (log == null)
            {
                return NotFound();
            }
            return View(log);
        }

        // POST: Logs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,GarageNumber,ContractNumber,BookNumber,ReleaseDate")] Log log)
        {
            if (id != log.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(log);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LogExists(log.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(log);
        }

        // GET: Logs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var log = await _context.Log
                .SingleOrDefaultAsync(m => m.Id == id);
            if (log == null)
            {
                return NotFound();
            }

            return View(log);
        }

        // POST: Logs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var log = await _context.Log.SingleOrDefaultAsync(m => m.Id == id);
            _context.Log.Remove(log);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LogExists(int id)
        {
            return _context.Log.Any(e => e.Id == id);
        }
    }
}

GarageCooperative/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ПАСК "Загорье-5"</title>
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ПАСК "Загорье-5"</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">О нас</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Контакты</a></li>
                    <!-- <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Управление ГК<b class="caret"></b></a>
        <ul class="dropdown-menu multi-level">
            <li><a asp-area="" asp-controller="Owners" asp-action="Index"> Управление </a></li>
            <li><a asp-area="" asp-controller="Debits" asp-action="Index"> Доход (Только для бухгалтера) </a></li>
            <li><a asp-area="" asp-controller="Credits" asp-action="Index"> Расходы (Только для бухгалтера) </a></li>
            <li><a asp-area="" asp-controller="Journals" asp-action="Index"> Журнал посещений </a></li>
            <li><a asp-area="" asp-controller="Logs" asp-action="Index"> Журнал Отчетов </a></li>
            <li><a asp-area="" asp-controller="Contacts" asp-action="Index"> Администрирование </a></li>
        </ul>
    </li>
    -->
                    @await Html.PartialAsync("_MenuPartial")
                </ul>
                @await Html.PartialAsync("_LoginPartial")
               
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ПАСК "Загорье-5"</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

GarageCooperative/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using GarageCooperative.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using GarageCooperative.Models;

@if (SignInManager.IsSignedIn(User) && !UserManagerExtensions.FindByNameAsync(UserManager, User).ChangePassword)
{
    @if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Администратор"))
    {
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Управление ГК<b class="caret"></b></a>
            <ul class="dropdown-menu multi-level">
                <li><a asp-area="" asp-controller="Owners" asp-action="Index"> Члены кооператива </a></li>
                <li><a asp-area="" asp-controller="Boxes" asp-action="Index"> Боксы </a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Sms"> Смс-рассылка </a></li>
                <li><a asp-area="" asp-controller="Cars" asp-action="Index"> Проверка проезжающих машин </a></li>
                <li><a asp-area="" asp-controller="ElectricMeterReadings" asp-action="Index"> Показания электрических счетчиков </a></li>
                <li><a asp-area="" asp-controller="ArrivalJournals" asp-action="Index"> Журнал посещений </a></li>
                <li><a asp-area="" asp-controller="EventJournals" asp-action="Index"> Журнал происшествий </a></li>
                <li><a asp-area="" asp-controller="Users" asp-action="Index"> Администрирование </a></li>
            </ul>
        </li>
    }
    @if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Бухгалтер"))
    {
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Управление ГК<b class="caret"></b></a>
            <ul class="dropdown-menu multi-level">
                <li><a asp-area="" asp-controller="Debits" asp-action="Index"> Доход (Только для бухгалтера) </a></li>
                <li><a asp-area="" asp-controller="Credits" asp-action="Index"> Расходы (Только для бухгалтера) </a></li>
            </ul>
        </li>
    }
    @if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Охранник"))
    {
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Управление ГК<b class="caret"></b></a>
            <ul class="dropdown-menu multi-level">
                <li><a asp-area="" asp-controller="Cars" asp-action="Index"> Проверка проезжающих машин </a></li>
                <li><a asp-area="" asp-controller="ArrivalJournals" asp-action="Index"> Журнал посещений </a></li>
                <li><a asp-area="" asp-controller="EventJournals" asp-action="Index"> Журнал происшествий </a></li>
            </ul>
        </li>
    }

@if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Председатель"))
{
    <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Управление ГК<b class="caret"></b></a>
        <ul class="dropdown-menu multi-level">
            <li><a asp-area="" asp-controller="Owners" asp-action="Index"> Члены кооператива </a></li>
            <li><a asp-area="" asp-controller="Boxes" asp-action="Index"> Боксы </a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Sms"> Смс-рассылка </a></li>
            <li><a asp-area="" asp-controller="Cars" asp-action="Index"> Проверка проезжающих машин </a></li>
            <li><a asp-area="" asp-controller="ElectricMeterReadings" asp-action="Index"> Показания электрических счетчиков </a></li>
            <li><a asp-area="" asp-controller="ArrivalJournals" asp-action="Index"> Журнал посещений </a></li>
            <li><a asp-area="" asp-controller="EventJournals" asp-action="Index"> Журнал происшествий </a></li>
        </ul>
    </li>
}
@if (await SignInManager.UserManager.IsInRoleAsync(UserManagerExtensions.FindByNameAsync(UserManager, User), "Электрик"))
{
    <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Управление ГК<b class="caret"></b></a>
        <ul class="dropdown-menu multi-level">
            <li><a asp-area="" asp-controller="ElectricMeterReadings" asp-action="Index"> Показания электрических счетчиков </a></li>
        </ul>
    </li>
}
}